version = 1

exclude_patterns = ["vendor/**"]

test_patterns = ["tests/**"]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "github.com/ishan-deepsource/psalm-analyzer"
enabled = true
